import { format } from "date-fns";
import { useDraggable } from "@dnd-kit/core";
import { cn } from "@/lib/utils";
import { ImageIcon, Video, Images, Smartphone, Wrench, Clipboard } from "lucide-react";

interface ContentPillProps {
  content: {
    id: string;
    title: string;
    date: string;
    status: string;
    type: string;
    client_id: string;
    itemType?: 'content' | 'creative_request' | 'adjustment_request';
  };
  clientColor: string;
  onClick: (contentId: string) => void;
  isDragging?: boolean;
}

// Função para obter o rótulo do tipo
const getTypeLabel = (type: string): string => {
  const typeMap: Record<string, string> = {
    feed: "Feed",
    reels: "Reels",
    carousel: "Carrossel",
    story: "Story",
    image: "Feed", // Fallback
    video: "Reels", // Fallback
  };
  return typeMap[type.toLowerCase()] || type;
};

// Função para obter o ícone do tipo
const getTypeIcon = (type: string) => {
  const normalizedType = type.toLowerCase();
  
  if (normalizedType === 'feed' || normalizedType === 'image') {
    return ImageIcon;
  }
  if (normalizedType === 'reels' || normalizedType === 'video') {
    return Video;
  }
  if (normalizedType === 'carousel') {
    return Images;
  }
  if (normalizedType === 'story') {
    return Smartphone;
  }
  
  // Fallback para ImageIcon
  return ImageIcon;
};

// Função para verificar se o título é um título automático gerado (deve ser tratado como sem título)
const isAutoGeneratedTitle = (title: string): boolean => {
  if (!title || !title.trim()) return true;
  
  const trimmedTitle = title.trim();
  
  // Padrão: "Conteúdo DD/MM/YYYY HH:mm" ou variações
  // Exemplos: "Conteúdo 28/11/2025 08:00", "Conteúdo 28/11/2025 8:00", etc.
  // Aceita com ou sem zero à esquerda na hora
  const autoTitlePattern = /^Conteúdo\s+\d{1,2}\/\d{1,2}\/\d{4}\s+\d{1,2}:\d{2}$/;
  return autoTitlePattern.test(trimmedTitle);
};

export function ContentPill({ content, clientColor, onClick, isDragging = false }: ContentPillProps) {
  const { attributes, listeners, setNodeRef, transform, isDragging: isCurrentlyDragging } = useDraggable({
    id: content.id,
  });

  const style = transform ? {
    transform: `translate3d(${transform.x}px, ${transform.y}px, 0)`,
    opacity: isCurrentlyDragging ? 0.5 : 1,
  } : undefined;

  const isRequest = content.itemType === 'creative_request' || content.itemType === 'adjustment_request';

  // Lógica de exibição conforme as regras
  let displayContent: React.ReactNode;

  if (content.itemType === 'adjustment_request') {
    // Ajuste Criativo: [ícone chave] Ajuste Criativo
    displayContent = (
      <>
        <Wrench className="h-3 w-3 flex-shrink-0" />
        <span className="flex-1 min-w-0 leading-tight">Ajuste Criativo</span>
      </>
    );
  } else if (content.itemType === 'creative_request') {
    // Solicitação de criativo: [ícone clipboard] + título
    displayContent = (
      <>
        <Clipboard className="h-3 w-3 flex-shrink-0" />
        <span className="flex-1 min-w-0 leading-tight">{content.title}</span>
      </>
    );
  } else {
    // Conteúdo normal
    const hasTitle = content.title && content.title.trim() !== '';
    const isAutoTitle = hasTitle && isAutoGeneratedTitle(content.title);
    const effectiveHasTitle = hasTitle && !isAutoTitle; // Título válido (não é auto-gerado)
    const timeStr = format(new Date(content.date), 'HH:mm'); // Sem colchetes
    
    const TypeIcon = getTypeIcon(content.type);
    
    if (!effectiveHasTitle) {
      // Sem título válido: exibir ícone + hora + tipo (hora sempre visível quando disponível)
      displayContent = (
        <>
          <TypeIcon className="h-3 w-3 flex-shrink-0" />
          <span className="font-medium whitespace-nowrap flex-shrink-0">{timeStr}</span>
          <span className="flex-1 min-w-0 leading-tight">{getTypeLabel(content.type)}</span>
        </>
      );
    } else {
      // Com título válido: exibir ícone + hora + título
      displayContent = (
        <>
          <TypeIcon className="h-3 w-3 flex-shrink-0" />
          <span className="font-medium whitespace-nowrap flex-shrink-0">{timeStr}</span>
          <span className="flex-1 min-w-0 leading-tight">{content.title}</span>
        </>
      );
    }
  }

  return (
    <div
      ref={setNodeRef}
      style={{
        ...style,
        backgroundColor: clientColor,
        color: 'white',
        textShadow: '0 1px 2px rgba(0,0,0,0.2)'
      }}
      className={cn(
        "text-xs px-2 py-1 rounded cursor-move hover:opacity-80 transition-opacity touch-none",
        "flex items-start gap-1 break-words",
        isCurrentlyDragging && "opacity-50",
        isRequest && "ring-2 ring-offset-1 ring-yellow-500"
      )}
      onClick={(e) => {
        if (!isCurrentlyDragging) {
          e.stopPropagation();
          onClick(content.id);
        }
      }}
      title={content.title || getTypeLabel(content.type)}
      {...attributes}
      {...listeners}
    >
      {displayContent}
    </div>
  );
}
